---
- name: enable webserver
  hosts: ansible1.example.com
  tasks:
  - name:  install httpd and firewalld
    yum:
      name: 
      - httpd
      - firewalld
      state: latest
  - name: install welcome page
    copy:
      content: "hello world"
      dest: /var/www/html/index.html
  - name: start web services
    service:
      name: httpd
      state: started
      enabled: yes
  - name: start firewalld services
    service:
      name: firewalld
      state: started
      enabled: yes
  - name: open firewalld
    firewalld:
      service: http
      permanent: yes
      immediate: yes
      state: enabled

- name: test webserver access
  hosts: localhost
  become: no
  tasks:
  - name: connect to the web server
    uri:
      url: http://ansible1.example.com
      return_content: yes 
      status_code: 200
